apiVersion: v1
kind: Secret
metadata:
  name: devops-demo-argocd-vault-credentials-argo-vault
  annotations:
    avp.kubernetes.io/path: "secret/data/devops-prod/dbinfo"
#    avp.kubernetes.io/remove-missing: "true"
type: Opaque
data:
  NAME_1: <name | base64encode>
  PASSWORD_1: <passwod | base64encode>
  TTL_1: <ttl | base64encode>
