apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: consul-agent-demo2
spec:
  protocol: "http"

---
apiVersion: v1
kind: Service
metadata:
  name: consul-agent-demo2
spec:
  selector:
    app: consul-agent-demo2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-agent-demo2-account
  labels:
    app: consul-agent-demo2
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-agent-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consul-agent-demo2
      app: consul-agent-demo2
  template:
    metadata:
      labels:
        service: consul-agent-demo2
        app: consul-agent-demo2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/envoy-extra-args: '--log-level debug --disable-hot-restart'
#        consul.hashicorp.com/connect-service-upstreams: "product-api:8080"
        consul.hashicorp.com/enable-metrics-merging: "false"
        consul.hashicorp.com/service-tags: devops,consul

        sidecar.istio.io/inject: "false"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "consul-agent-demo2-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/devops-dev/dbinfo"
        vault.hashicorp.com/agent-inject-secret-foo: 'secret/devops-dev/foo'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/devops-dev/dbinfo" -}}
             db_id: "{{ .Data.data.name }}"
             db_password: "{{ .Data.data.passwod }}"
          {{- end }}
          {{ with secret "secret/devops-dev/foo" -}}
             db_id2: "{{ .Data.data.name }}"
             db_password2: "{{ .Data.data.passwod }}"
          {{- end }}
    spec:
      serviceAccountName: consul-agent-demo2-account
      containers:
      - name: consul-agent-demo2
        image: nginx
      nodeSelector:
        team: devops
        environment: consul
