apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-prod-svcaccount
  namespace: devops
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo
  namespace: argocd
spec:
  destination:
    namespace: devops
    server: https://kubernetes.default.svc
  project: devops
  source:
    path: devops-demo/prod
    repoURL: https://github.com/tzkr/tz-argocd-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
