apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-dev-svcaccount
  namespace: devops-dev
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-tz-demo-app
  namespace: argocd
spec:
  destination:
    namespace: devops-dev
    server: https://kubernetes.default.svc
  project: devops-dev
  source:
    path: devops-tz-demo-app/dev
    repoURL: https://github.com/doohee323/tz-argocd-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
