apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-dev-svcaccount
  namespace: devops-dev
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-devops-demo
  namespace: argocd
spec:
  destination:
    namespace: devops-dev
    server: https://kubernetes.default.svc
  project: devops-dev
  source:
    path: devops-devops-demo/dev
    repoURL: https://github.com/tzkr/tz-argocd-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
