apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-demo-account
  labels:
    app: vault-agent-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-demo
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-agent-demo
    spec:
      containers:
      - name: vault-agent-demo
        image: nginx

