apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-demo2-account
  labels:
    app: vault-agent-demo2

---

apiVersion: v1
kind: Service
metadata:
  name: vault-agent-demo2
spec:
  selector:
    app: vault-agent-demo2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-demo2
  labels:
    app: vault-agent-demo2
spec:
  selector:
    matchLabels:
      app: vault-agent-demo2
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-agent-demo2
      annotations:
        sidecar.istio.io/inject: "false"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-agent-demo2-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/devops-dev/dbinfo"
        vault.hashicorp.com/agent-inject-secret-foo: 'secret/devops-dev/foo'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/devops-dev/dbinfo" -}}
             db_id: "{{ .Data.data.name }}"
             db_password: "{{ .Data.data.passwod }}"
          {{- end }}
          {{ with secret "secret/devops-dev/foo" -}}
             db_id2: "{{ .Data.data.name }}"
             db_password2: "{{ .Data.data.passwod }}"
          {{- end }}
    spec:
      serviceAccountName: vault-agent-demo2-account
      containers:
      - name: vault-agent-demo2
        image: nginx

