apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-devops-web
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-devops-web
  namespace: devops-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: ebs-sc-devops-web
  volumeMode: Filesystem
