kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-list
rules:
- apiGroups: [""]
  resources: ["namespaces", "customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops
  name: devops-manager
rules:
- apiGroups: ["", "metrics.k8s.io", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops
  name: devops-manager
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "events"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets","persistentvolumeclaims", "daemonsets", "replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "services", "statefulsets", "events"]
  verbs: ["get", "list", "watch", "update"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops-dev
  name: devops-manager-dev
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
