apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    local_connect_timeout_ms: 1000
    handshake_timeout_ms: 10000
#    envoy_prometheus_bind_addr: '0.0.0.0:9102'
#    members: 3
#  meshGateway:
#    mode: local

---

#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ProxyDefaults
#metadata:
#  name: global
#  annotations:
#    'consul.hashicorp.com/migrate-entry': 'true'
#spec:
#  meshGateway:
#    mode: local
#  config:
#    local_connect_timeout_ms: 1000
#    handshake_timeout_ms: 10000

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: tz-consul-service
spec:
  protocol: 'http'

---

