apiVersion: v1
kind: Service
metadata:
  name: product-api-new
spec:
  selector:
    app: product-api-new
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api-new
automountServiceAccountToken: true

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api-new
spec:
  protocol: "http"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap-new
data:
  config: |
    {
      "db_connection": "host=127.0.0.1 port=5432 user=postgres password=password dbname=products sslmode=disable",
      "bind_address": ":9090",
      "metrics_address": ":9103"
    }
---