global:
  name: consul
  enabled: true
  datacenter: tz-dc
  tls:
    enabled: false
    httpsOnly: false
  metrics:
    enabled: true
    enableAgentMetrics: true
  scrape_interval:  5s
  scrape_timeout: 3s

server:
  replicas: 1
  bootstrapExpect: 1
  storageClass: gp2
  storage: 50Gi
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  service:
    enabled: true
  resources:
    requests:
      memory: "400Mi"
      cpu: "400m"
    limits:
      memory: "3Gi"
      cpu: "2"
  nodeSelector: |
    team: devops
    environment: consul
  imagePullSecrets:
    - name: "tz-registrykey"
  extraConfig: |
    {
      "enable_central_service_config": false,
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-server"
        }
      }
    }
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

ui:
  enabled: true
  service:
    enabled: true
    type: 'ClusterIP'

connectInject:
  enabled: true
  default: false
  metrics:
    defaultEnableMerging: true
#  centralConfig:
#    enabled: false

# Enable CRD Controller
controller:
  enabled: true

prometheus:
  enabled: true

client:
  enabled: true
  extraConfig: |
    {"enable_central_service_config": false}

