apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-devops-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-devops-web
  resources:
    requests:
      storage: 1Gi
#  volumeMode: Filesystem
#  volumeName: ebs-pv-devops-web

#---
#
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: ebs-pv-devops-web
#spec:
#  accessModes:
#  - ReadWriteMany
#  awsElasticBlockStore:
#    fsType: xfs
#    volumeID: aws://ap-northeast-1a/vol-074777954c77a4fe2
#  capacity:
#    storage: 10Mi
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: ebs-sc-devops-web
#  volumeMode: Filesystem
