apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-parallel-job
  generateName: kube-job-
  labels:
    jobgroup: jobexample
spec:
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: kubernetes-parallel-job
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: REPOSITORY_TAG
        args: ["100"]
      restartPolicy: OnFailure