apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: devops-demo-dev
  namespace: devops-dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: devops-demo-dev
  targetNamespace: devops-dev
  chart:
    repository: s3://tz-helm-devops-demo-helm-bucket/charts
    name: devops-demo-helm
    version: 0.1.9
  values:
    master:
      resources:
         limits:
           cpu: 100m
           memory: 128Mi
         requests:
           cpu: 100m
           memory: 128Mi
