apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
name: devops-demo-prod
namespace: devops-prod
spec:
releaseName: devops-demo-prod
chart:
  repository: https://tzkr.github.io/tz-helm-charts/
  name: devops-demo-helm
  version: 0.1.10
values:
  master:
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"