apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaling-test
  name: scaling-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scaling-test
  template:
    metadata:
      labels:
        app: scaling-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 700m
            memory: 500Mi
      nodeSelector:
        team: devops
        environment: dev

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-test
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: scaling-test
    apiVersion: apps/v1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10

