
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: jenkins.default.eks_project.eks_domain
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
