apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-v1
  labels:
    app: product-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
      version: v1
  template:
    metadata:
      labels:
        app: product-api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "postgres:5432"
        consul.hashicorp.com/enable-metrics-merging: "false"
        consul.hashicorp.com/service-meta-version: v1
        consul.hashicorp.com/service-tags: devops,dev
    spec:
      serviceAccountName: product-api
      volumes:
      - name: config
        configMap:
          name: db-configmap-new
          items:
          - key: config
            path: conf.json
      containers:
        - name: product-api
          image: hashicorpdemoapp/product-api:v0.0.12
          ports:
            - containerPort: 9090
            - containerPort: 9103
          env:
            - name: "CONFIG_FILE"
              value: "/config/conf.json"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      nodeSelector:
        team: devops
        environment: consul
