global:
  imagePullSecrets: ["tz-registrykey"]
  storageClass: "gp2"
  postgresql:
    postgresqlDatabase: "tlive_dev"
    postgresqlUsername: "postgres"
    postgresqlPassword: "rootsql"

image:
  repository: bitnami/postgresql
  pullPolicy: IfNotPresent
  pullSecrets: ["tz-registrykey"]

postgresqlPostgresPassword: "rootsql"
postgresqlDatabase: "tlive_dev"
postgresqlUsername: "postgres"
postgresqlPassword: "rootsql"

service:
  type: LoadBalancer

persistence:
  enabled: true
  storageClass: "gp2"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

primary:
  nodeSelector:
    team: "devops"
    environment: "prod"

readReplicas:
  nodeSelector:
    team: devops
    environment: prod

resources:
  requests:
    memory: 256Mi
    cpu: 250m

