# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devops-dev"
        vault.hashicorp.com/agent-inject-secret-config: "secret/devops/database"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/devops/database" -}}
              {{ range $k, $v := .Data.data }}
                  {{ $k }}: {{ $v }}
              {{ end }}
          {{ end }}
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: devops-dev-svcaccount
      containers:
      - name: vault-demo
        image: nginx

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-dev-svcaccount
  labels:
    app: vault-agent-demo
