kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-NS
  annotations:
    volume.beta.kubernetes.io/storage-class: efs-NS
spec:
  storageClassName: efs-NS
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: efs-busybox
spec:
  volumes:
  - name: efs-site
    persistentVolumeClaim:
      claimName: efs-NS
  containers:
    - name: efs-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      volumeMounts:
        - name: efs-site
          mountPath: /efs-volume
  nodeSelector:
    team: TEAM
    environment: STAGING
