efsProvisioner:
  efsFileSystemId: "file_system_id"
  awsRegion: "AWS_REGION"
  path: /efs-vol-root
#  provisionerName: kubernetes.io/aws-efs
  provisionerName: "example.com/aws-efs"
  storageClass:
    name: efs-NS
    reclaimPolicy: Retain

serviceAccount:
  create: false
  name: "efs-provisioner-sa"

podAnnotations:
  iam.amazonaws.com/role: "arn:aws:iam::aws_account_id:role/eks_role"

nodeSelector:
  team: TEAM
  environment: STAGING
