alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_from: devops@tz.gg
      smtp_smarthost: smtp.gmail.com:587
      smtp_auth_username: devops@tz.gg
      smtp_auth_password: admin_password
      smtp_require_tls: true
      slack_api_url: https://hooks.slack.com/services/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
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: devops-admin
      routes:
    #      - receiver: 'devops-admin'
    #        match:
    #          alertname: Watchdog
    #  - receiver: 'devops-dev'
    #    match:
    #      instance: http://tz-sample-app.devops-dev.svc
      - receiver: devops-dev
        match:
          team: devops_dev
    #  - receiver: 'devops-prod'
    #    match:
    #      instance: http://tz-sample-app.devops.svc
      - receiver: devops-prod
        match:
          team: devops_prod
#      - match:
#          alertname: Watchdog
#          receiver: "null"
#      - match:
#          alertname: CPUThrottlingHigh
#        receiver: "null"
    receivers:
    - name: devops-admin
      slack_configs:
      - send_resolved: true
        channel: eks-alert
        title: |-
          {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
        text: '{{ template "slack.default.text" . }}'
      email_configs:
      - send_resolved: true
        to: devops@tz.gg
    - name: devops-dev
      slack_configs:
      - send_resolved: true
        channel: eks-alert
        title: |-
          {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
        text: '{{ template "slack.default.text" . }}'
      email_configs:
      - send_resolved: true
        to: doohee.hong@tz.kr
    - name: devops-prod
      slack_configs:
      - send_resolved: true
        channel: eks-alert
        title: |-
          {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
        text: '{{ template "slack.default.text" . }}'
      email_configs:
      - send_resolved: true
        to: doohee323@gmail.com
    templates:
    - /etc/alertmanager/config/*.tmpl
  alertmanagerSpec:
    externalUrl: https://alertmanager.default.eks_project.eks_domain
    nodeSelector:
      environment: prod
      team: devops
#    affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#         - matchExpressions:
#           - key: kubernetes.io/e2e-az-name
#             operator: In
#             values:
#             - e2e-az1
#             - e2e-az2
#    podAntiAffinity: ""
#    podAntiAffinityTopologyKey: kubernetes.io/hostname
