apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sample-app-down
spec:
  groups:
  - name: "sample-app-down.rules"
    rules:
    - alert: sample-app-down
      expr: count(kube_pod_status_phase{pod=~"tz-sample-app.*", phase="Failed"}) by (namespace) == 0
      for: 1m
      annotations:
        message: |
          `{{ $labels.namespace }}/{{ $labels.pod }}` is down.
      labels:
        severity: critical
