apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz-sample-app
spec:
  selector:
    matchLabels:
      app: tz-sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tz-sample-app
        team: devops_prod
    spec:
      containers:
      - name: tz-sample-app
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---

---
apiVersion: v1
kind: Service
metadata:
  name: tz-sample-app
spec:
  type: NodePort
  selector:
    app: tz-sample-app
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-tz-sample-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: tz-sample-prod.default.eks_project.eks_domain
    http:
      paths:
      - path: /
        backend:
          serviceName: tz-sample-app
          servicePort: 80
  tls:
    - hosts:
        - tz-sample-prod.default.eks_project.eks_domain
      secretName: ingress-tz-sample-prod-tls
